# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-10-19 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parametros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parametros',
            new_name='Parametro',
        ),
    ]
