# Generated by Django 2.1 on 2020-12-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_servico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='servico',
            new_name='texto1',
        ),
    ]
