# Generated by Django 2.1 on 2020-12-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_sobre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto1', models.TextField()),
                ('texto2', models.TextField()),
            ],
        ),
    ]
